### ISSUE TITLE
cannot load such file rubygems/util

### ISSUE THREAD

**Issue by tbrooke** [alindeman/rails4_upgrade#7]
I am on a Mac:
  High Sierra 10.13
 zsh 
 .rbenv
 ruby 1.9.3-p448
rails 3.2.12

I get the following both with bundle exec and without

rake aborted!
cannot load such file -- rubygems/util
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `block in require'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/unicode-display_width-1.3.2/lib/unicode/display_width/index.rb:1:in `<top (required)>'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/unicode-display_width-1.3.2/lib/unicode/display_width.rb:2:in `require_relative'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/unicode-display_width-1.3.2/lib/unicode/display_width.rb:2:in `<top (required)>'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `block in require'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/terminal-table-1.8.0/lib/terminal-table/cell.rb:1:in `<top (required)>'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `block in require'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/terminal-table-1.8.0/lib/terminal-table.rb:25:in `block in <top (required)>'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/terminal-table-1.8.0/lib/terminal-table.rb:24:in `each'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/terminal-table-1.8.0/lib/terminal-table.rb:24:in `<top (required)>'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `block in require'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/bundler/gems/rails4_upgrade-2e39e8e55507/lib/rails4_upgrade/formatters/incompatible_gems_formatter.rb:1:in `<top (required)>'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `block in require'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/bundler/gems/rails4_upgrade-2e39e8e55507/lib/rails4_upgrade/formatters.rb:1:in `<top (required)>'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `block in require'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
/Users/tmb/msm/food-pantry-manager/vendor/bundle/bundler/gems/rails4_upgrade-2e39e8e55507/lib/rails4_upgrade.rb:4:in `<top (required)>'
/Users/tmb/msm/food-pantry-manager/config/application.rb:14:in `<top (required)>'
/Users/tmb/msm/food-pantry-manager/Rakefile:5:in `require'
/Users/tmb/msm/food-pantry-manager/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by tbrooke** [comment]
Fixed it 

did a gem/update --system
